# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [16]:
import pandas as pd
import matplotlib.pyplot as plt

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [92]:
df=pd.read_csv('https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/chipotle.tsv', sep='\t')

In [82]:
df.head(3)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39

### Step 3. Assign it to a variable called chipo.

In [93]:
chipo=df

### Step 4. See the first 10 entries

In [20]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [21]:
# Solution 1
chipo.shape

(4622, 5)

In [22]:
# Solution 2

chipo.count()

order_id              4622
quantity              4622
item_name             4622
choice_description    3376
item_price            4622
dtype: int64

In [9]:
chipo.value_counts('item_name')

item_name
Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Chips                                    211
Steak Bowl                               211
Bottled Water                            162
Chicken Soft Tacos                       115
Chips and Fresh Tomato Salsa             110
Chicken Salad Bowl                       110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Crispy Tacos                      47
Chips and Tomatillo Green Chili Salsa     43
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        35
Chips and Tomatillo-Green Chili Salsa     31
Steak Salad Bowl                          29
Nantucket Nectar                          27
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        22
Izze                                      20
Chips and Tomatillo-Red Chili Salsa       20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      7
Veggie Soft Tacos                          7
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Steak Salad                                4
Bowl                                       2
Crispy Tacos                               2
Salad                                      2
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Carnitas Salad                             1
Name: count, dtype: int64

In [15]:
# chipo.value_counts()

In [23]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

### Step 6. What is the number of columns in the dataset?

In [24]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [25]:
list(chipo.columns)

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

### Step 8. How is the dataset indexed?

In [26]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

In [27]:
chipo.set_index('order_id', inplace=True)

In [28]:
chipo.index

Index([   1,    1,    1,    1,    2,    3,    3,    4,    4,    5,
       ...
       1831, 1831, 1831, 1832, 1832, 1833, 1833, 1834, 1834, 1834],
      dtype='int64', name='order_id', length=4622)

In [29]:
chipo.head(3)

          quantity                     item_name choice_description item_price
order_id
1                1  Chips and Fresh Tomato Salsa                NaN     $2.39
1                1                          Izze       [Clementine]     $3.39
1                1              Nantucket Nectar            [Apple]     $3.39

In [30]:
chipo.reset_index(inplace=True)

In [32]:
chipo.head(3)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39

### Step 9. Which was the most-ordered item?

In [34]:
df['item_name'].value_counts().head(1)

item_name
Chicken Bowl    726
Name: count, dtype: int64

In [34]:
gr=df.groupby('item_name')['quantity'].sum()
gr=pd.DataFrame(gr)
gr.sort_values('quantity', ascending=False).head(1)

              quantity
item_name
Chicken Bowl       761

In [35]:
gr.reset_index(inplace=True)

In [36]:
gr[gr.quantity == gr.quantity.max()]['item_name'].values[0]

'Chicken Bowl'

### Step 10. For the most-ordered item, how many items were ordered?

In [47]:
gr=df.groupby('item_name')['quantity'].sum()
gr=pd.DataFrame(gr)
int(gr['quantity'].max())

761

### Step 11. What was the most ordered item in the choice_description column?

In [48]:
df.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [63]:
gr2=pd.DataFrame(df.groupby('choice_description')['quantity'].sum())
gr2.head(5)
gr2[gr2.quantity==gr2.quantity.max()]

                    quantity
choice_description
[Diet Coke]              159

### Step 12. How many items were orderd in total?

In [65]:
total_items=df.quantity.sum()
int(total_items)

4972

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [75]:
chipo['item_price'].dtype

#### Step 13.b. Create a lambda function and change the type of item price

In [94]:
float_func=lambda x : float(x)

result=[ float_func(x[1:]) for x in list(df['item_price']) ]

In [97]:
df['item_price']=result

In [99]:
df.head(5)

,order_id,quantity,item_name,choice_description,item_price,item_price2
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,16.98

In [ ]:
# dollarizer = lambda x: float(x[1:-1])
# chipo.item_price = chipo.item_price.apply(dollarizer)

#### Step 13.c. Check the item price type

In [100]:
df['item_price'].dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [102]:
chipo['revenue_generated']=chipo['quantity']*chipo['item_price']

In [109]:
total_revenue=chipo['revenue_generated'].sum()
print("$"+str(float(total_revenue)))

$39237.02

### Step 15. How many orders were made in the period?

In [113]:
chipo.order_id.value_counts().count()

np.int64(1834)

### Step 16. What is the average revenue amount per order?

In [115]:
# Solution 1
average_amount_per_order=(chipo['revenue_generated'].sum())/(chipo.order_id.value_counts().count())
float(average_amount_per_order)

21.39423118865867

In [ ]:
# Solution 2
chipo.groupby('order_id')['revenue'].sum().mean()
# Solution 3

chipo['revenue'] = chipo['quantity'] * chipo['item_price']
order_grouped = chipo.groupby(by=['order_id']).sum()
order_grouped.mean()['revenue']

### Step 17. How many different items are sold?

In [120]:
float(df.item_name.value_counts().count())

50.0

In [119]:
df.item_name.value_counts()

item_name
Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Chips                                    211
Steak Bowl                               211
Bottled Water                            162
Chicken Soft Tacos                       115
Chips and Fresh Tomato Salsa             110
Chicken Salad Bowl                       110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Crispy Tacos                      47
Chips and Tomatillo Green Chili Salsa     43
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        35
Chips and Tomatillo-Green Chili Salsa     31
Steak Salad Bowl                          29
Nantucket Nectar                          27
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        22
Izze                                      20
Chips and Tomatillo-Red Chili Salsa       20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      7
Veggie Soft Tacos                          7
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Steak Salad                                4
Bowl                                       2
Crispy Tacos                               2
Salad                                      2
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Carnitas Salad                             1
Name: count, dtype: int64